SELECT * 
FROM 
    OPENQUERY(E6_NODO_ORIENTE, 
    'SELECT * 
     FROM OPENQUERY(MYSQL_8, 
     ''
     SELECT 
         SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS CASOS_DIABETES, 
         SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS CASOS_HIPERTENSION, 
         SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS CASOS_OBESIDAD, 
         COUNT(*) AS CASOS_TOTALES, 
         ''''ORIENTE'''' AS REGION 
     FROM e6_covid_oriente.datoscovid 
     WHERE CLASIFICACION_FINAL IN (1, 2, 3)
     '')
    ') 
UNION
SELECT *
FROM OPENQUERY(E6_NODO_NORTE, 
	'
	SELECT 
         SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS CASOS_DIABETES, 
         SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS CASOS_HIPERTENSION, 
         SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS CASOS_OBESIDAD, 
         COUNT(*) AS CASOS_TOTALES, 
         ''NORTE'' AS REGION 
     FROM e6_covid_norte.dbo.datoscovid 
     WHERE CLASIFICACION_FINAL IN (1, 2, 3)
	')
UNION
SELECT *
FROM OPENQUERY(E6_NODO_OCCIDENTE_Y_OTROS, 
	'
	SELECT 
         SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS CASOS_DIABETES, 
         SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS CASOS_HIPERTENSION, 
         SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS CASOS_OBESIDAD, 
         COUNT(*) AS CASOS_TOTALES, 
         ''OCCIDENTE Y OTROS'' AS REGION 
     FROM e6_covid_occidente_y_otros.dbo.datoscovid 
     WHERE CLASIFICACION_FINAL IN (1, 2, 3)
	')
UNION
SELECT *
FROM OPENQUERY(E6_NODO_SUR, 
	'
	SELECT 
         SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS CASOS_DIABETES, 
         SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS CASOS_HIPERTENSION, 
         SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS CASOS_OBESIDAD, 
         COUNT(*) AS CASOS_TOTALES, 
         ''SUR'' AS REGION 
     FROM e6_covid_sur.dbo.datoscovid 
     WHERE CLASIFICACION_FINAL IN (1, 2, 3)
	')
;
